### ISSUE TITLE
Замечания

### ISSUE THREAD

**Issue by gagarski** [Stoncs/FirstJava#1]
1. Хорошо бы ваши классы переместить из default package в отдельный пакет
2. Класс `Position` возвращается из публичных методов `TicTacToe`, а значит не длжен быть package-private
3. Начиная с main код уехал куда-то вправо.
4. Для крестика/нолика/пустой строки есть более подходящий тип, чем строка. В таких случаях лучше использовать перечисления (`enum`)
5. Попробуйте избавиться от копипасты в `spider` (там сейчас четыре одинаковых куска кода)
6. `Object[]` - это такой себе тип возвращаемого значения. Если нужно вернуть два разнородных объекта, заведите вложенный приватный класс.
7. https://github.com/Stoncs/FirstJava/blob/c492cfa9854861180fc5f540f37a1f6e8cb25e8b/src/TicTacToe.java#L116

Эту константу лучше вынести в класс и сделать приватной и статической. 

8. https://github.com/Stoncs/FirstJava/blob/c492cfa9854861180fc5f540f37a1f6e8cb25e8b/src/TicTacToe.java#L136

Раз то же самое, то зачем скопировали?

9. В `desk` у вас не поле, а размер. Лучше бы чтобы название соответствовало.

10. Разумно было бы добавить метод, вовзращающий значение ячейки по координатам. Тогда и само поле можно сделать приватным.

**Comment by Stoncs** [comment]
Не могу понять, как выполнить пятый пункт. В одном цикле номер столбца увеличивается, а номер строки не меняется, в другом наоборот. В циклах, проверяющих диагонали, похожее. В одном номер строки и столбца увеличивается, в другом - номер столбца увеличивается, а номер строки уменьшается.

**Comment by gagarski** [comment]
> В одном цикле номер столбца увеличивается, а номер строки не меняется

В одном цикле номер столбца увеличивается на один, а в другом на ноль. И так далее. Так понятнее?:)

Ещё немного мелких замечаний образовалось после исправления тех (ну или в результате того, что я проглядел их раньше):

1. Value слишком пространное название для класса.
2. Вместо `show`, печатающего поле, лучше переопределить стандартный toString. Тогда вы сможете печатать поле, просто передав его в println.
3.  `ForSpider` можно сделать приватным: он не принимается как аргумент и не возвращается из публичных методов. Также такие классы можно упрощать: сделать поля неприватными, а геттеры убрать. Почему тут можно, а в других нельзя (и когда нельзя) готов пояснить на занятии.

**Comment by Stoncs** [comment]
Ок, всё исправил
